$('.monster-blue').find('img').on('mouseenter',function(e){
    $(this).attr('src','./img/talk.gif')
})
$('.monster-blue').find('img').on('mouseleave',function(e){
    $(this).attr('src','./img/talk.png')
})
$('.inner-nav-ul').find('img').on('mouseenter',function(){
    $(this).attr('src','./img/lm.jpg')
})
$('.inner-nav-ul').find('img').on('mouseleave',function(){
    $(this).attr('src','./img/small.jpg')
})
$('.contact-img1').find('img').on('mouseenter',function(){
    $(this).attr('src','./img/footer/qq2-hover.png')
})
$('.contact-img1').find('img').on('mouseleave',function(){
    $(this).attr('src','./img/footer/qq2.png')
})
$('.contact-img2').find('img').on('mouseenter',function(){
    $(this).attr('src','./img/footer/qq3-hover.png')
})
$('.contact-img2').find('img').on('mouseleave',function(){
    $(this).attr('src','./img/footer/qq3.png')
})